### ISSUE TITLE
Feedback - Region Hardcoded

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Enterprise-class-networking#42] opened 2019-11-18 16:34 UTC
In the steps wherever we are deploying resources, it is mentioned to use region South Central US in the HOL Guide. But, it will be better if you can modify the guide to use the region where the Resource Group is deployed.

**Comment by paulopsgility** [comment] 2019-12-03 00:56
@amalgireesh Can you elaborate on this request? we frequently specify specific regions to guarantee that the lab works as intended. We can take another look at the next scheduled update but I want to make sure there is not some other compelling issue you are trying to fix other than a resource group having resources in multiple regions (which is perfectly valid).

**Comment by paulopsgility** [comment] 2019-12-09 22:16
Marking as enhancement for visibility. We'll take a look at the next test/fix to see if we still need the region hard coded.

**Comment by paulopsgility** [comment] 2020-03-05 18:36
@amalgireesh The regions in the lab purposefully align with the scenario in the whiteboard design session. We also need multiple regions for the lab. You are welcome to choose other regions if you dont care about the WDS alignment but we are going to leave this as is for the official lab to avoid any potential misunderstandings during lab execution.

**Closed by paulopsgility** 2020-03-05 18:36 UTC
Labels: enhancement
